- src/main/java/kcs/funding/fundingboost/domain/entity/Bookmark.java
- src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
[FB-4](https://kcsfinalproject.atlassian.net/browse/FB-4)
[FB-4]: https://kcsfinalproject.atlassian.net/browse/FB-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨Feat: 찜목록, GiftHub, 주문 Entity   생성

- src/main/java/kcs/funding/fundingboost/domain/entity/Contributor.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
- src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
펀딩, 펀딩아이템, 펀딩기여자 엔티티 추가
[FB-3]: https://kcsfinalproject.atlassian.net/browse/FB-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: 펀딩, 펀딩아이템, 펀딩기여자 엔티티 추가

- src/main/java/domain/entity/Delivery.java
- src/main/java/domain/entity/Item.java
Entity 패키지에 Item, Delivery 클래스 생성 
[FB-2](https://kcsfinalproject.atlassian.net/browse/FB-2)
[FB-2]: https://kcsfinalproject.atlassian.net/browse/FB-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: Item, Delivery Entity 생성

- src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Relationship.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Review.java
개요
Entity 패키지에 Item, Delivery 클래스 생성
변경사항
새로운 기능 추가
버그 수정
CSS 등 사용자 UI 디자인 변경
코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
코드 리팩토링
주석 추가 및 수정
문서 수정
테스트 추가, 테스트 리팩토링
빌드 부분 혹은 패키지 매니저 수정
파일 혹은 폴더명 수정
파일 혹은 폴더 삭제
관련 지라 및 위키 링크
[FB-1](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-1)
리뷰어에게 하고 싶은 말
[FB-1]: https://kcsfinalproject.atlassian.net/browse/FB-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: Member, Review, Relationship Entity 생성

- src/main/java/kcs/funding/fundingboost/domain/entity/Bookmark.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Contributor.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Delivery.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
- src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
- src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Relationship.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Review.java
[FB-2](https://kcsfinalproject.atlassian.net/browse/FB-2)
merge 해주세요...ㅎㅎ
[FB-2]: https://kcsfinalproject.atlassian.net/browse/FB-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: Item, Delivery 클래스 @DynamicUpdate 어노테이션 제거 및 Bookmark, Contributor 등의 클래스 @OnDelete 어노테이션 추가

- build.gradle
- src/main/java/kcs/funding/fundingboost/domain/config/AuditConfig.java
- src/main/java/kcs/funding/fundingboost/domain/config/QueryDslConfig.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Bookmark.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Contributor.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Delivery.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
- src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
- src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Relationship.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Review.java
- src/main/java/kcs/funding/fundingboost/domain/entity/common/BaseTimeEntity.java
- src/main/java/kcs/funding/fundingboost/domain/repository/BookmarkRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/ContributorRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/DeliveryRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/FundingItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/FundingRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/GiftHubItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/ItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/MemberRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/OrderRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/RelationshipRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/ReviewRepository.java
[FB-num](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-19)
> ✨ Feat: 공통 Repository 생성 & Querydsl 설정 추가 & BaseTimeEntity 추가

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubItemController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/GiftHubDto.java
- src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
- src/main/java/kcs/funding/fundingboost/domain/repository/GiftHubItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
- src/main/resources/application.yml
[FB-num](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-13)
---
- Member 1명
- Item 3개
- GiftHubItem 2개
---
> ✨ Feat: GiftHub 페이지 조회 & dummy Data 추가

- src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubItemController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/common/commonSuccessDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/request/AddGiftHubDto.java
- src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
[FB-num](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-9)
---
###
ex. "memberId = 1"인 유저가 "itemId=3"인 아이템을 GiftHub에 수량 25개를 담음.
> ✨ Feat: GiftHub 담기 기능 추가

- src/main/java/kcs/funding/fundingboost/domain/controller/ItemController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/ShopDto.java
- src/main/java/kcs/funding/fundingboost/domain/entity/GiftHubItem.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
- src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
> ✨ Feat: 쇼핑 페이지 조회

- src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
> ✨ Feat: 펀딩 종료하기 기능 추가

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/controller/MyPayController.java
[FB-14](https://kcsfinalproject.atlassian.net/browse/FB-14)
ResponseDto로 바꿔야 했는데 깜빡했네용~><(엣큥)
[FB-14]: https://kcsfinalproject.atlassian.net/browse/FB-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🎨Refactor: ResponseDto로 return 수정

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/controller/MyPayController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/request/PaymentDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/DeliveryDto.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Delivery.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
- src/main/java/kcs/funding/fundingboost/domain/service/PaymentService.java
[FB-15](https://kcsfinalproject.atlassian.net/browse/FB-15)
결제하기 페이지 구현, deliveryDto에서 deliveryId를 가져와야 배송상태 수정이 가능해서 수정했습니당
[FB-15]: https://kcsfinalproject.atlassian.net/browse/FB-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨🎨  Feat/Refactor: 결제하기 구현 및 deliveryDto 수정

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/controller/FriendPayController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/DeliveryDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingPayingDto.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
- src/main/java/kcs/funding/fundingboost/domain/service/FriendPayService.java
[FB-30](https://kcsfinalproject.atlassian.net/browse/FB-30)
승인해주시죵
테스트 결과는 confluence API 명세서 참고 ><
[FB-30]: https://kcsfinalproject.atlassian.net/browse/FB-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: 친구 펀딩 결제 페이지 조회

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Item.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
[FB-37](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-37)
더미 데이터 리팩토링 했어요~
- 멤버 추가
- 아이템은 카테고리 뷰티만 삽입
[FB-37]: https://kcsfinalproject.atlassian.net/browse/FB-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨Refactor: 더미 데이터 삽입

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/controller/FriendPayController.java
- src/main/java/kcs/funding/fundingboost/domain/controller/MyPayController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/request/FriendPayProcessDto.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Member.java
- src/main/java/kcs/funding/fundingboost/domain/service/FriendPayService.java
[FB-29](https://kcsfinalproject.atlassian.net/browse/FB-29)
[FB-29]: https://kcsfinalproject.atlassian.net/browse/FB-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: 친구 펀딩 결제하기

- src/main/java/kcs/funding/fundingboost/domain/repository/FundingItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
- src/main/java/kcs/funding/fundingboost/domain/service/MyPayService.java
[FB-14](https://kcsfinalproject.atlassian.net/browse/FB-14)
Funding 객체로 찾는 걸 funding_id 키값을 이용하여 찾도록 수정했습니다.
테스트도 완료했어용
[FB-14]: https://kcsfinalproject.atlassian.net/browse/FB-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨Refactor: Funding 객체로 찾는 걸 funding_id 키값을 이용하여 찾도록 수정

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/main/java/kcs/funding/fundingboost/domain/service/MyPayService.java
---
1. 배송지 관련 더미 데이터 추가
2. ERD 수정 적용 (Order Entity)
> 🔨Refactor: ERD 수정 반영하기 & 더미 데이터 배송지 추가

- src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
- src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
- src/main/java/kcs/funding/fundingboost/domain/controller/HomeController.java
- src/main/java/kcs/funding/fundingboost/domain/controller/ItemController.java
- src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
- src/main/java/kcs/funding/fundingboost/domain/controller/PayController.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
* Controller의 URL Mapping 수정
* OSIV off인 경우를 생각하여 controller에 있던 @Transactional 애노테이션 service로 이동
[FB-39](https://kcsfinalproject.atlassian.net/browse/FB-39)
[FB-39]: https://kcsfinalproject.atlassian.net/browse/FB-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 Refactor: API 명세 수정에 따른 Contorller URL mapping 수정 및 주석 추가

- src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/request/RegisterFundingDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/request/RegisterFundingItemDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/CommonFriendFundingDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingPageItemDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/HomeFriendFundingDto.java
- src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
- src/main/java/kcs/funding/fundingboost/domain/repository/FundingItem/FundingItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
- src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepositoryCustom.java
- src/main/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepositoryRepositoryImpl.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/main/java/kcs/funding/fundingboost/domain/service/HomeService.java
친구 목록 페이지 & 메인 페이지 조회 충돌 및 깃 dev 브랜치와 충돌 해결
[FB-46](https://kcsfinalproject.atlassian.net/browse/FB-46)
기다려줘서 감사함둥ㅎㅎ
[FB-46]: https://kcsfinalproject.atlassian.net/browse/FB-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 refactor: 친구 목록 페이지 & 메인 페이지 조회 충돌 및 깃 dev 브랜치와 충돌 해결

- src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
- src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/CommonFriendFundingDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/FriendFundingDetailDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/MyFundingHistoryDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/MyFundingResponseDto.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Tag.java
- src/main/java/kcs/funding/fundingboost/domain/repository/Contributor/ContributorRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/Contributor/ContributorRepositoryCustom.java
- src/main/java/kcs/funding/fundingboost/domain/repository/Contributor/ContributorRepositoryImpl.java
- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryCustom.java
- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
[FB-49](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-49)
---
[FB-49]: https://kcsfinalproject.atlassian.net/browse/FB-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: 지난 펀딩 이력 조회

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/MyFundingHistoryDetailDto.java
- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
- src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
지난 펀딩 이력 상세 조회 기능 개발 
funding이 진행중일 때 funding 아이디로 잘못 조회 했을 때는 ErrorCode : 40009 message : 펀딩이 정상적이지 않습니다. 
h2 테스트 코드에 member 1과 member 5, 6의 친구 관계 추가
[FB-50](https://kcsfinalproject.atlassian.net/browse/FB-50)
[FB-50]: https://kcsfinalproject.atlassian.net/browse/FB-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: 지난 펀딩 이력 상세 조회 기능 개발

- src/main/java/kcs/funding/fundingboost/domain/dto/response/MyPayViewDto.java
- src/main/java/kcs/funding/fundingboost/domain/exception/ErrorCode.java
- src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
> :ambulance: [HotFix] dev 에러 수정

- src/main/java/kcs/funding/fundingboost/domain/config/CorsConfig.java
- src/main/java/kcs/funding/fundingboost/domain/config/WebMVCConfig.java
[FB-62](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-62)
CORS 관련 설정 추가했습니다!
[FB-62]: https://kcsfinalproject.atlassian.net/browse/FB-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔧 [Config] CORS 설정 추가

- src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/deliveryManage/MyPageDeliveryDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/deliveryManage/MyPageDeliveryManageDto.java
- src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
마이페이지 배송지 관리 조회 기능 구현
[FB-57](https://kcsfinalproject.atlassian.net/browse/FB-57)
[FB-57]: https://kcsfinalproject.atlassian.net/browse/FB-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: 마이페이지 배송지 관리 조회 기능 구현

- src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
- src/main/java/kcs/funding/fundingboost/domain/repository/GiftHubItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/service/GiftHubItemService.java
Gifthub 상품 삭제 기능 구현
[FB-55](https://kcsfinalproject.atlassian.net/browse/FB-55)
[FB-55]: https://kcsfinalproject.atlassian.net/browse/FB-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ feat: Gifthub 상품 삭제 기능 구현

- src/main/java/kcs/funding/fundingboost/Init/InitH2DB.java
- src/main/java/kcs/funding/fundingboost/domain/controller/MyPageController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/ItemDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/MyWishListDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/WishtListItemDto.java
- src/main/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepository.java
- src/main/java/kcs/funding/fundingboost/domain/service/MyPageService.java
[FB-58](https://kcsfinalproject.atlassian.net/browse/FB-58)
[FB-58]: https://kcsfinalproject.atlassian.net/browse/FB-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨Feat: feat: 위시리스트 조회 기능 구현

- src/main/java/kcs/funding/fundingboost/domain/dto/request/RegisterFundingDto.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
Funding deadline dto 수정 
[FB-71](https://kcsfinalproject.atlassian.net/browse/FB-71)
[FB-71]: https://kcsfinalproject.atlassian.net/browse/FB-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 Refactor : Funding deadline dto 수정 

- src/test/java/kcs/funding/fundingboost/domain/service/OrderServiceTest.java
[FB-66](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-66)
[FB-66]: https://kcsfinalproject.atlassian.net/browse/FB-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ Test: OrderService 테스트 코드 작성

- src/test/java/kcs/funding/fundingboost/domain/service/pay/FriendPayServiceTest.java
[FB-68](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-68)
[FB-68]: https://kcsfinalproject.atlassian.net/browse/FB-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ Test: FriendPayService 테스트 코드 작성

- src/main/java/kcs/funding/fundingboost/domain/controller/BookmarkController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/wishList/BookmarkItemDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/wishList/MyBookmarkListDto.java
- src/main/java/kcs/funding/fundingboost/domain/service/BookmarkService.java
> 🔨 Refactor: bookmark로 이름 통일

- src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
[FB-65](https://kcsfinalproject.atlassian.net/browse/FB-65)
[FB-65]: https://kcsfinalproject.atlassian.net/browse/FB-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 Refactor: fundingItem을 생성할 때 funding에 fundingItem을 추가

- src/main/java/kcs/funding/fundingboost/domain/controller/GiftHubController.java
- src/test/java/kcs/funding/fundingboost/domain/controller/GiftHubControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/model/GiftHubItemFixture.java
[FB-83](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-83)
[FB-83]: https://kcsfinalproject.atlassian.net/browse/FB-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ GiftHubController Junit Test 구현

- src/test/java/kcs/funding/fundingboost/domain/controller/ItemControllerTest.java
[FB-84](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-84)
[FB-84]: https://kcsfinalproject.atlassian.net/browse/FB-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ ItemController Junit Test 구현

- src/test/java/kcs/funding/fundingboost/domain/model/DeliveryFixture.java
- src/test/java/kcs/funding/fundingboost/domain/service/DeliveryServiceTest.java
[FB-76](https://kcsfinalproject.atlassian.net/browse/FB-76)
[FB-76]: https://kcsfinalproject.atlassian.net/browse/FB-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ 🔨 Test/Refactor: 창희 DeliveryService 테스트 코드 통합

- src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
- src/main/java/kcs/funding/fundingboost/domain/entity/OrderItem.java
- src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
- src/test/java/kcs/funding/fundingboost/domain/controller/OrderControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/model/OrderFixture.java
[FB-86](https://kcsfinalproject.atlassian.net/browse/FB-86)
[FB-86]: https://kcsfinalproject.atlassian.net/browse/FB-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ 🔨 Test/Refactor: 창희 OrderController 테스트 코드  추가 및 Order/OrderItem totalPrice 추가 로직 refactor

- src/main/java/kcs/funding/fundingboost/domain/controller/MemberController.java
- src/test/java/kcs/funding/fundingboost/domain/controller/MemberControllerTest.java
[FB-93](https://kcsfinalproject.atlassian.net/browse/FB-93)
[FB-93]: https://kcsfinalproject.atlassian.net/browse/FB-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ 🔨 Test/Refactor: 창희 MemberController 테스트 코드 통합

- src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/myFundingStatus/MyFundingStatusDto.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
마이페이지 내 펀딩 현황 funding message, tag 추가
[FB-95](https://kcsfinalproject.atlassian.net/browse/FB-95)
[FB-95]: https://kcsfinalproject.atlassian.net/browse/FB-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 refactor: 마이페이지 내 펀딩 현황 funding message, tag 추가

- src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/home/HomeMyFundingStatusDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/home/HomeViewDto.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Contributor.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Funding.java
- src/main/java/kcs/funding/fundingboost/domain/entity/FundingItem.java
- src/main/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/main/java/kcs/funding/fundingboost/domain/service/MemberService.java
- src/main/java/kcs/funding/fundingboost/domain/service/pay/FriendPayService.java
- src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
- src/main/java/kcs/funding/fundingboost/domain/service/utils/DateUtils.java
- src/main/java/kcs/funding/fundingboost/domain/service/utils/FundingConst.java
- src/main/java/kcs/funding/fundingboost/domain/service/utils/FundingUtils.java
- src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
- src/test/java/kcs/funding/fundingboost/domain/controller/DeliveryControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/controller/GiftHubControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/controller/OrderControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/model/FundingFixture.java
- src/test/java/kcs/funding/fundingboost/domain/model/FundingItemFixture.java
- src/test/java/kcs/funding/fundingboost/domain/model/GiftHubItemFixture.java
- src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest.java
- src/test/java/kcs/funding/fundingboost/domain/service/MemberServiceTest.java
- src/test/java/kcs/funding/fundingboost/domain/service/pay/FriendPayServiceTest.java
[FB-96](https://kcsfinalproject.atlassian.net/browse/FB-96)
[FB-96]: https://kcsfinalproject.atlassian.net/browse/FB-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🚑 HotFix: 충돌 에러 수정

- src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
> 🔨 refactor: initDB 리팩토링

- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
FundingService 메인 페이지 & 마이 펀딩 현황 조회에서 아이템 Percent 로직 오류 수정
[FB-102](https://kcsfinalproject.atlassian.net/browse/FB-102)
{
"success": true,
"data": {
"myPageMemberDto": {
"nickName": "구태형",
"email": "rnxogud136@gmail.com",
"profileImgUrl": "https://p.kakaocdn.net/th/talkp/wowkAlwbLn/Ko25X6eV5bs1OycAz7n9Q1/lq4mv6_110x110_c.jpg",
"point": 999999999
},
"myPageFundingItemDtoList": [
{
"fundingId": 2,
"itemName": "NEW 루쥬 알뤼르 벨벳 뉘 블랑쉬 리미티드 에디션",
"itemPrice": 61000,
"itemImageUrl": "https://img1.kakaocdn.net/thumb/C320x320@2x.fwebp.q82/?fname=https%3A%2F%2Fst.kakaocdn.net%2Fproduct%2Fgift%2Fproduct%2F20240319133310_1fda0cf74e4f43608184bce3050ae22a.jpg",
"optionName": "00:00",
"itemPercent": 100,
"finishedStatus": true
},
{
"fundingId": 2,
"itemName": "NEW 루쥬 코코 밤(+샤넬 기프트 카드)",
"itemPrice": …
> 🔨 refactor: FundingService 메인 페이지 & 마이 펀딩 현황 조회에서 아이템 Percent 로직 오류 수정

- src/test/java/kcs/funding/fundingboost/domain/controller/MemberControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/controller/OrderControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/controller/PayControllerTest.java
[FB-100](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-100)
[FB-100]: https://kcsfinalproject.atlassian.net/browse/FB-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  ✅ PayController(friendPayView, fundFriend) Test 코드 구현

- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/service/utils/DateUtilsTest.java
- src/test/java/kcs/funding/fundingboost/domain/service/utils/FundingUtilsTest.java
- src/test/java/kcs/funding/fundingboost/domain/service/utils/PayUtilsTest.java
[FB-103](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-103)
1. createDate / deadLine 관련 코드 리팩토링 진행
2. Utils 테스트 코드 작성
[FB-103]: https://kcsfinalproject.atlassian.net/browse/FB-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ 🔨 Test/Refactor: Utils 테스트 코드 작성 및 createDate, deadLine 관련 테스트 코드 수정

- src/main/java/kcs/funding/fundingboost/domain/dto/response/home/HomeMyFundingStatusDto.java
- src/main/java/kcs/funding/fundingboost/domain/service/utils/DateUtils.java
- src/main/java/kcs/funding/fundingboost/domain/service/utils/FundingConst.java
- src/test/java/kcs/funding/fundingboost/domain/service/utils/DateUtilsTest.java
> ✨ 🔨 Feat/Refactor: 메인페이지 조회시 사용자 테그 출력/ 시간 차이를 이용하여 펀딩종료 표현을 하기 위해 시간차를 LocalDate -> LocalDateTime으로 변경 및 펀딩 종료명 수정

- src/main/java/kcs/funding/fundingboost/domain/service/utils/DateUtils.java
> 🔨 Refactor: 시간 차이를 이용하여 펀딩종료 상태요소 추가

- src/main/java/kcs/funding/fundingboost/domain/controller/BookmarkController.java
- src/test/java/kcs/funding/fundingboost/domain/controller/BookmarkControllerTest.java
[FB-75](https://kcsfinalproject.atlassian.net/browse/FB-75)
[FB-75]: https://kcsfinalproject.atlassian.net/browse/FB-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ Test: Bookmark Controller test code 구현

- src/main/java/kcs/funding/fundingboost/domain/entity/Delivery.java
- src/test/java/kcs/funding/fundingboost/domain/model/FundingFixture.java
- src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTestCH.java
- src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest_InHo_v2.java
Delivery deliveryStatus 삭제 및 테스트 코드 오류 수정
[FB-107](https://kcsfinalproject.atlassian.net/browse/FB-107)
[FB-107]: https://kcsfinalproject.atlassian.net/browse/FB-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 ✅ refactor: Delivery deliveryStatus 삭제 및 테스트 코드 오류 수정

- src/main/java/kcs/funding/fundingboost/domain/service/pay/MyPayService.java
mypay fundingItem 배송지 입력하기에서 funding 진행중인 기준을 deadline으로 변경
[FB-108](https://kcsfinalproject.atlassian.net/browse/FB-108)
[FB-108]: https://kcsfinalproject.atlassian.net/browse/FB-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 refactor: mypay fundingItem 배송지 입력하기에서 funding 진행중인 기준을 deadline으로 변경

- src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
- src/main/java/kcs/funding/fundingboost/domain/config/SwaggerConfig.java
- src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/fundingRegist/FundingRegisterStatusDto.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
- src/test/resources/application.yml
펀딩 등록 페이지를 조회할 때 해당 사용자의 펀딩의 유무를 조회하여 ResposeBody로 전달해준다.
또한 Swagger를 Security환경에서 Token을 넣어서 Test를 하기 위한 설정
Test에서 DB를 사용하기 위한 application.yml 추가
[FB-115](https://kcsfinalproject.atlassian.net/browse/FB-115)
[FB-115]: https://kcsfinalproject.atlassian.net/browse/FB-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat 펀딩 등록 페이지를 조회할 때 해당 사용자의 펀딩 유무 확인

- src/main/java/kcs/funding/fundingboost/domain/dto/response/giftHub/GiftHubDto.java
GiftHub 페이지 조회할 때 GiftHubItemId 추가
[FB-116](https://kcsfinalproject.atlassian.net/browse/FB-116)
[FB-116]: https://kcsfinalproject.atlassian.net/browse/FB-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 Refactor: GiftHub 페이지 조회할 때 GiftHubItemId 추가

- src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
- src/main/java/kcs/funding/fundingboost/domain/controller/ItemController.java
- src/main/java/kcs/funding/fundingboost/domain/security/resolver/JwtAuthorizationArgumentResolver.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/main/java/kcs/funding/fundingboost/domain/service/ItemService.java
home, 쇼핑, 쇼핑 디테일 페이지 로그인x 사용자 접근 허용
[FB-118](https://kcsfinalproject.atlassian.net/browse/FB-118)
[FB-118]: https://kcsfinalproject.atlassian.net/browse/FB-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 refactor: home, 쇼핑, 쇼핑 디테일 페이지 로그인x 사용자 접근 허용

- src/main/java/kcs/funding/fundingboost/domain/controller/FundingController.java
- src/main/java/kcs/funding/fundingboost/domain/controller/MemberController.java
- src/test/java/kcs/funding/fundingboost/domain/controller/GiftHubControllerTest.java
memberId @Login 어노테이션으로 수정 및 GiftHubCOntrollerTest 변경된 로직에 따른 parameter 값 수정
> 🔨 refactor: memberId @Login 어노테이션으로 수정 및 GiftHubCOntrollerTest 변경된 로직에 따른 parameter 값 수정

- src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
- src/main/java/kcs/funding/fundingboost/domain/security/resolver/JwtAuthorizationArgumentResolver.java
- src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
> 🔨 Feat/fb 109

- .gitignore
- build.gradle
- src/main/java/kcs/funding/fundingboost/domain/config/AuthenticationConfig.java
- src/main/java/kcs/funding/fundingboost/domain/config/SecurityConfig.java
- src/main/java/kcs/funding/fundingboost/domain/config/WebMVCConfig.java
- src/main/java/kcs/funding/fundingboost/domain/dto/global/ResponseDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/request/login/LoginDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/login/JwtDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/login/JwtTokenDto.java
- src/main/java/kcs/funding/fundingboost/domain/repository/MemberRepository.java
- src/main/java/kcs/funding/fundingboost/domain/security/CustomUserDetails.java
- src/main/java/kcs/funding/fundingboost/domain/security/CustomUserDetailsService.java
- src/main/java/kcs/funding/fundingboost/domain/security/KakaoOAuth2User.java
- src/main/java/kcs/funding/fundingboost/domain/security/controller/OAuth2AuthenticationController.java
- src/main/java/kcs/funding/fundingboost/domain/security/controller/SimpleAuthenticationController.java
- src/main/java/kcs/funding/fundingboost/domain/security/handler/OAuth2AuthenticationFailureHandler.java
- src/main/java/kcs/funding/fundingboost/domain/security/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/kcs/funding/fundingboost/domain/security/provider/SimpleAuthenticationProvider.java
- src/main/java/kcs/funding/fundingboost/domain/security/service/SimpleAuthenticationService.java
- src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
- src/main/java/kcs/funding/fundingboost/domain/service/CustomOAuth2UserService.java
- src/main/java/kcs/funding/fundingboost/init/InitH2DB.java
- src/main/resources/application.yml
- src/main/resources/templates/loginForm.html
[FB-112](https://kcsfinalproject.atlassian.net/browse/FB-112)
[FB-112]: https://kcsfinalproject.atlassian.net/browse/FB-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: oauth 2.0 로그인 추가

- .gitignore
- build.gradle
- src/main/java/kcs/funding/fundingboost/domain/config/SwaggerConfig.java
- src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
- src/main/resources/application.yml
> 🔨 Refactor: git ignore 수정 및 swagger config Refresh Token 입력할 수 있도록 수정

- build.gradle
- src/main/java/kcs/funding/fundingboost/domain/security/entity/BlackList.java
- src/main/java/kcs/funding/fundingboost/domain/security/repository/BlackListRepository.java
- src/main/java/kcs/funding/fundingboost/domain/security/service/JwtAuthenticationService.java
- src/main/java/kcs/funding/fundingboost/domain/security/service/RedisTemplateService.java
- src/main/java/kcs/funding/fundingboost/domain/security/utils/NoAuthPath.java
- src/main/resources/application.yml
[FB-124](https://kcsfinalproject.atlassian.net/browse/FB-124)
[FB-124]: https://kcsfinalproject.atlassian.net/browse/FB-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐞 fix : Redis AccessToken BlackList TTL 적용 안되는 버그 수정

- src/main/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepository.java
- src/test/java/kcs/funding/fundingboost/domain/model/BookmarkFixture.java
- src/test/java/kcs/funding/fundingboost/domain/repository/MemberRepositoryTest.java
- src/test/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepositoryImplTest.java
- src/test/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepositoryTest.java
- src/test/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepositoryImplTest.java
- src/test/java/kcs/funding/fundingboost/domain/repository/giftHubItem/GiftHubItemRepositoryTest.java
- src/test/resources/application.yml
GiftHubItem. Bookmark, Member Repository Test 구현
[FB-123](https://kcsfinalproject.atlassian.net/browse/FB-123)
[FB-123]: https://kcsfinalproject.atlassian.net/browse/FB-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Feat: GiftHubItem. Bookmark, Member Repository Test 구현

- src/main/java/kcs/funding/fundingboost/domain/repository/fundingItem/FundingItemRepository.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/test/java/kcs/funding/fundingboost/domain/repository/DeliveryRepositoryTest.java
- src/test/java/kcs/funding/fundingboost/domain/repository/ItemRepositoryTest.java
- src/test/java/kcs/funding/fundingboost/domain/repository/fundingItem/FundingItemRepositoryTest.java
- src/test/java/kcs/funding/fundingboost/domain/repository/orderItem/OrderItemRepositoryImplTest.java
- src/test/java/kcs/funding/fundingboost/domain/repository/relationship/RelationshipRepositoryTest.java
- src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTestCH.java
- src/test/java/kcs/funding/fundingboost/domain/service/FundingServiceTest_InHo_v2.java
- src/test/resources/application.yml
[FB-121](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/issues/FB-121)
[FB-121]: https://kcsfinalproject.atlassian.net/browse/FB-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ Test: Delivery, Item, relationship, fundingItem repository 테스트 코드 작성

- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepository.java
- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryCustom.java
- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
- src/main/java/kcs/funding/fundingboost/domain/service/MemberService.java
- src/test/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryTest.java
- src/test/java/kcs/funding/fundingboost/domain/service/MemberServiceTest.java
[FB-130
](https://kcsfinalproject.atlassian.net/browse/FB-130)
>  ✅ Test: FundingRepository Test Code 생성 및 중복된 기능의 QueryDsl 제거 및 기존 Jsql로 대체

- .gitignore
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/test/java/kcs/funding/fundingboost/domain/repository/bookmark/BookmarkRepositoryImplTest.java
- src/test/resources/application.yml
[FB-133](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-133)
- MyPayService의 @SpringBootTest를 없애고 @ExtendWith(MockitoExtension.class)를 넣어 테스트가 통과하도록 코드 리팩해야돼요!
---
[FB-133]: https://kcsfinalproject.atlassian.net/browse/FB-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> :ambulance: [HotFix] dev 브랜치 에러 수정 

- src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/myFundingStatus/MyPageFundingItemDto.java
- src/main/java/kcs/funding/fundingboost/domain/dto/response/pay/myPay/MyOrderPayViewDto.java
- src/main/java/kcs/funding/fundingboost/domain/service/FundingService.java
- src/test/java/kcs/funding/fundingboost/domain/controller/FundingControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/controller/PayControllerTest.java
- src/test/java/kcs/funding/fundingboost/domain/service/pay/MyPayServiceTest.java
[FB-135](https://kcsfinalproject.atlassian.net/jira/software/projects/FB/boards/2?selectedIssue=FB-135)
[FB-135]: https://kcsfinalproject.atlassian.net/browse/FB-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 refactor: 마이페이지 조회 시 itemStatus 추가 및 deliveryListDto로 dto 이름 변경

- src/main/java/kcs/funding/fundingboost/domain/dto/response/myPage/myFundingStatus/MyPageFundingItemDto.java
마이페이지 My펀딩현황에서 FundingItemId 추가
[FB-137](https://kcsfinalproject.atlassian.net/browse/FB-137)
[FB-137]: https://kcsfinalproject.atlassian.net/browse/FB-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🔨 refactor: 마이페이지 My펀딩현황에서 FundingItemId 추가

- build.gradle
- src/main/java/kcs/funding/fundingboost/domain/config/CorsConfig.java
- src/main/java/kcs/funding/fundingboost/domain/entity/Order.java
- src/main/java/kcs/funding/fundingboost/domain/repository/funding/FundingRepositoryImpl.java
[FB-138](https://kcsfinalproject.atlassian.net/browse/FB-138)
[FB-138]: https://kcsfinalproject.atlassian.net/browse/FB-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> :ambulance: [Conflict] conflict solved
